In [ ]:
import plotly.express as px #express-class inside the plotly
x1=[1,2,3,4,5]
y1=[1,23,4,5,6]
fig=px.line(x=x1,y=y1,title="sample")
fig.show()

In [ ]:
#https://plotly.com/python/     (graphing library)

In [ ]:
import numpy as np
x_=np.random.randint(1,100,100)
y_=np.random.randint(1,100,100)
fig=px.bar(x=x_,y=y_)
fig.show()

In [ ]:
x_

array([38, 68,  5, 30, 73, 32, 23, 21,  7, 56, 55, 18, 29, 76, 43, 68,  3,
       86, 35, 74, 43, 93, 16,  7, 39, 58, 78, 23,  8, 50, 40, 71, 12, 31,
       81,  5, 48, 77, 93, 80, 45, 76, 60, 32, 96, 73, 55, 12, 40, 89, 50,
       81, 65, 55, 40, 32, 68, 13,  5, 54, 73, 29, 98,  4, 49, 15, 45, 99,
       92, 63, 97, 28, 95, 44, 40, 92, 72, 73, 10,  5, 51, 91, 75, 76, 68,
       76, 57, 49, 12,  5, 72, 83, 47, 77, 75, 59, 79, 94, 72, 20])

In [ ]:
y_

array([53,  2, 30,  8, 70, 46, 16, 16, 28,  5, 85, 93,  2, 64, 71, 87, 97,
       61, 29, 67, 18,  5, 52, 45, 97, 42, 23, 70, 72, 63, 76, 52, 76, 73,
       40, 50, 27, 42, 87, 27, 26, 39, 72, 86, 48, 97, 45, 71, 45, 22, 48,
       35, 39, 27, 57, 89, 12,  3, 65, 75, 55, 58, 28, 20, 83, 49,  6, 18,
       33, 87, 74, 53, 33, 29, 34, 91, 73, 16, 72, 47, 73, 76, 78, 45, 97,
       38, 26, 94, 72, 34,  5, 67,  2, 23, 50, 97, 36, 21, 22, 34])

In [ ]:
fig=px.scatter(x_,y_)
fig.show()

In [ ]:
df=px.data.tips()
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
#HISTOGRAM
#Histogtram represents the frequency distribution
#example frequency/count of similar amount of tips
fig=px.histogram(df,x="tip")
fig.show()

In [ ]:
#smokers who gave the tip
fig=px.histogram(df,x="tip",color="smoker")
fig.show()

In [ ]:
fig=px.histogram(df,x="tip",color="size")
fig.show()

In [ ]:
fig=px.histogram(df,x="total_bill",color="smoker")
fig.show()

In [ ]:
fig=px.histogram(df,x="total_bill",color="smoker",marginal="violin")
fig.show()

In [ ]:
df1=px.data.iris()
df1

sepal_length  sepal_width  ...    species  species_id
0             5.1          3.5  ...     setosa           1
1             4.9          3.0  ...     setosa           1
2             4.7          3.2  ...     setosa           1
3             4.6          3.1  ...     setosa           1
4             5.0          3.6  ...     setosa           1
..            ...          ...  ...        ...         ...
145           6.7          3.0  ...  virginica           3
146           6.3          2.5  ...  virginica           3
147           6.5          3.0  ...  virginica           3
148           6.2          3.4  ...  virginica           3
149           5.9          3.0  ...  virginica           3

[150 rows x 6 columns]

In [ ]:
fig=px.scatter(df1,x="sepal_length",y="sepal_width",color="species",size="petal_length")
fig.show()

In [ ]:
fig=px.scatter(df1,x="sepal_length",y="sepal_width",color="species",size="species_id")
fig.show()

In [ ]:
fig=px.pie(values=x_,names=y_)
fig.show()

In [ ]:
#piegraph using plotly
# values(gets visulaised in %) and names
x=[111,2000,500]
y=["sample1","sample2","sample3"]
fig=px.pie(values=x,names=y)
fig.show()

In [ ]:
df1=px.data.iris()
df1

sepal_length  sepal_width  ...    species  species_id
0             5.1          3.5  ...     setosa           1
1             4.9          3.0  ...     setosa           1
2             4.7          3.2  ...     setosa           1
3             4.6          3.1  ...     setosa           1
4             5.0          3.6  ...     setosa           1
..            ...          ...  ...        ...         ...
145           6.7          3.0  ...  virginica           3
146           6.3          2.5  ...  virginica           3
147           6.5          3.0  ...  virginica           3
148           6.2          3.4  ...  virginica           3
149           5.9          3.0  ...  virginica           3

[150 rows x 6 columns]

In [ ]:
fig = px.pie(df1,values="sepal_width",names="species")
fig.show()

In [ ]:
fig=px.box(df1,x="sepal_width",y="sepal_length")
fig.show()

In [ ]:
import plotly.graph_objects as go

In [ ]:
fig=go.Figure(data = go.Scatterpolar(r=[1,2,3,4,5,6,7,8,9],theta=[69,141,213,285,357,429,501,573,645],mode="markers"))
fig.show()

In [ ]:
fig=go.Figure(data = go.Barpolar(r=[1,2,3,4,5,6,7,8,9],theta=[69,141,213,285,357,429,501,573,645]))
fig.show()

In [ ]:
fig=px.line_3d(df1,x="sepal_width",y="petal_length",z="petal_width",color="species")
fig.show()

In [ ]:
fig=px.scatter_3d(df1,x="sepal_width",y="petal_length",z="petal_width",color="species")
fig.show()

In [ ]:
import numpy as np
np.linspace(-5,5)  #linspace(x1,x2) returns a row vector of 100 evenly spaced points between x1 and x2.
#these values are nt randomly generated.
#they are equally divided and are generated using mean values

array([-5.        , -4.79591837, -4.59183673, -4.3877551 , -4.18367347,
       -3.97959184, -3.7755102 , -3.57142857, -3.36734694, -3.16326531,
       -2.95918367, -2.75510204, -2.55102041, -2.34693878, -2.14285714,
       -1.93877551, -1.73469388, -1.53061224, -1.32653061, -1.12244898,
       -0.91836735, -0.71428571, -0.51020408, -0.30612245, -0.10204082,
        0.10204082,  0.30612245,  0.51020408,  0.71428571,  0.91836735,
        1.12244898,  1.32653061,  1.53061224,  1.73469388,  1.93877551,
        2.14285714,  2.34693878,  2.55102041,  2.75510204,  2.95918367,
        3.16326531,  3.36734694,  3.57142857,  3.7755102 ,  3.97959184,
        4.18367347,  4.3877551 ,  4.59183673,  4.79591837,  5.        ])

In [ ]:
#linspace(x1,x2,n) generates n points. The spacing between the points is (x2-x1)/(n-1)
#“lin” in the name “linspace” refers to generating linearly spaced values as opposed to the sibling function logspace, 
#which generates logarithmically spaced values.
np.linspace(-5,5,7)

array([-5.        , -3.33333333, -1.66666667,  0.        ,  1.66666667,
        3.33333333,  5.        ])

In [ ]:
np.linspace(-30,30,30)

array([-30.        , -27.93103448, -25.86206897, -23.79310345,
       -21.72413793, -19.65517241, -17.5862069 , -15.51724138,
       -13.44827586, -11.37931034,  -9.31034483,  -7.24137931,
        -5.17241379,  -3.10344828,  -1.03448276,   1.03448276,
         3.10344828,   5.17241379,   7.24137931,   9.31034483,
        11.37931034,  13.44827586,  15.51724138,  17.5862069 ,
        19.65517241,  21.72413793,  23.79310345,  25.86206897,
        27.93103448,  30.        ])

In [ ]:
np.linspace(-30,30)

array([-30.        , -28.7755102 , -27.55102041, -26.32653061,
       -25.10204082, -23.87755102, -22.65306122, -21.42857143,
       -20.20408163, -18.97959184, -17.75510204, -16.53061224,
       -15.30612245, -14.08163265, -12.85714286, -11.63265306,
       -10.40816327,  -9.18367347,  -7.95918367,  -6.73469388,
        -5.51020408,  -4.28571429,  -3.06122449,  -1.83673469,
        -0.6122449 ,   0.6122449 ,   1.83673469,   3.06122449,
         4.28571429,   5.51020408,   6.73469388,   7.95918367,
         9.18367347,  10.40816327,  11.63265306,  12.85714286,
        14.08163265,  15.30612245,  16.53061224,  17.75510204,
        18.97959184,  20.20408163,  21.42857143,  22.65306122,
        23.87755102,  25.10204082,  26.32653061,  27.55102041,
        28.7755102 ,  30.        ])

In [ ]:
#The numpy.ones() function returns a new array of given shape and type, with ones.
np.ones(2)

array([1., 1.])

In [ ]:
(np.linspace(-30,30,30),np.ones(30))

(array([-30.        , -27.93103448, -25.86206897, -23.79310345,
        -21.72413793, -19.65517241, -17.5862069 , -15.51724138,
        -13.44827586, -11.37931034,  -9.31034483,  -7.24137931,
         -5.17241379,  -3.10344828,  -1.03448276,   1.03448276,
          3.10344828,   5.17241379,   7.24137931,   9.31034483,
         11.37931034,  13.44827586,  15.51724138,  17.5862069 ,
         19.65517241,  21.72413793,  23.79310345,  25.86206897,
         27.93103448,  30.        ]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [ ]:
#numpy.outer() function compute the outer product of two vectors.
np.outer(np.linspace(-1, 2, 4),np.ones(4))  

array([[-1., -1., -1., -1.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.]])

In [ ]:
np.outer(np.ones(4),np.linspace(-1, 2, 4))

array([[-1.,  0.,  1.,  2.],
       [-1.,  0.,  1.,  2.],
       [-1.,  0.,  1.,  2.],
       [-1.,  0.,  1.,  2.]])

In [ ]:
np.outer(4,2)

array([[8]])

In [ ]:
np.outer(4,[2,2])

array([[8, 8]])

In [ ]:
np.outer(4,np.ones(30))

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
        4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [ ]:
np.outer(np.linspace(-30,30,30),np.ones(30)) #values between np.linspace(-30,30,30) will be repeated 3O times

array([[-30.        , -30.        , -30.        , -30.        ,
        -30.        , -30.        , -30.        , -30.        ,
        -30.        , -30.        , -30.        , -30.        ,
        -30.        , -30.        , -30.        , -30.        ,
        -30.        , -30.        , -30.        , -30.        ,
        -30.        , -30.        , -30.        , -30.        ,
        -30.        , -30.        , -30.        , -30.        ,
        -30.        , -30.        ],
       [-27.93103448, -27.93103448, -27.93103448, -27.93103448,
        -27.93103448, -27.93103448, -27.93103448, -27.93103448,
        -27.93103448, -27.93103448, -27.93103448, -27.93103448,
        -27.93103448, -27.93103448, -27.93103448, -27.93103448,
        -27.93103448, -27.93103448, -27.93103448, -27.93103448,
        -27.93103448, -27.93103448, -27.93103448, -27.93103448,
        -27.93103448, -27.93103448, -27.93103448, -27.93103448,
        -27.93103448, -27.93103448],
       [-25.86206897, -25.8620

In [ ]:
np.outer(np.linspace(-2,2,30),np.ones(30))

array([[-2.        , -2.        , -2.        , -2.        , -2.        ,
        -2.        , -2.        , -2.        , -2.        , -2.        ,
        -2.        , -2.        , -2.        , -2.        , -2.        ,
        -2.        , -2.        , -2.        , -2.        , -2.        ,
        -2.        , -2.        , -2.        , -2.        , -2.        ,
        -2.        , -2.        , -2.        , -2.        , -2.        ],
       [-1.86206897, -1.86206897, -1.86206897, -1.86206897, -1.86206897,
        -1.86206897, -1.86206897, -1.86206897, -1.86206897, -1.86206897,
        -1.86206897, -1.86206897, -1.86206897, -1.86206897, -1.86206897,
        -1.86206897, -1.86206897, -1.86206897, -1.86206897, -1.86206897,
        -1.86206897, -1.86206897, -1.86206897, -1.86206897, -1.86206897,
        -1.86206897, -1.86206897, -1.86206897, -1.86206897, -1.86206897],
       [-1.72413793, -1.72413793, -1.72413793, -1.72413793, -1.72413793,
        -1.72413793, -1.72413793, -1.72413793, -1

In [ ]:
#3D SURFACE PLOT
import numpy as np
x=np.outer(np.linspace(-2,2,30),np.ones(30)) #(generate equally divided 30 values between -2 to 2 ,repeating them for 30 times )
y=x.copy().T #Transverse of matrix x
z=np.sin(x**2+y**2) 
#if x,y,z are interrelated only then they will form 3D surface graph

fig=go.Figure(data=[go.Surface(x=x,y=y,z=z)])
fig.show()

In [ ]:
x

array([[-2.        , -2.        , -2.        , -2.        , -2.        ,
        -2.        , -2.        , -2.        , -2.        , -2.        ,
        -2.        , -2.        , -2.        , -2.        , -2.        ,
        -2.        , -2.        , -2.        , -2.        , -2.        ,
        -2.        , -2.        , -2.        , -2.        , -2.        ,
        -2.        , -2.        , -2.        , -2.        , -2.        ],
       [-1.86206897, -1.86206897, -1.86206897, -1.86206897, -1.86206897,
        -1.86206897, -1.86206897, -1.86206897, -1.86206897, -1.86206897,
        -1.86206897, -1.86206897, -1.86206897, -1.86206897, -1.86206897,
        -1.86206897, -1.86206897, -1.86206897, -1.86206897, -1.86206897,
        -1.86206897, -1.86206897, -1.86206897, -1.86206897, -1.86206897,
        -1.86206897, -1.86206897, -1.86206897, -1.86206897, -1.86206897],
       [-1.72413793, -1.72413793, -1.72413793, -1.72413793, -1.72413793,
        -1.72413793, -1.72413793, -1.72413793, -1

In [ ]:
import numpy as np
x=np.outer(np.linspace(-2,2,30),np.ones(30)) #(generate equally divided 30 values between -2 to 2 ,repeating them for 30 times )
y=x.copy().T #Transverse of matrix x
z=np.tan(x**2+y**2)
#if x,y,z are interrelated only then they will form 3D surface graph

fig=go.Figure(data=[go.Surface(x=x,y=y,z=z)])
fig.show()

In [ ]:
# np.random.random() Return random floats in the half-open interval [0.0, 1.0)
np.random.random(100)

array([0.78302449, 0.1654136 , 0.22431169, 0.865636  , 0.05577244,
       0.74092337, 0.99763401, 0.5807721 , 0.05059805, 0.12073027,
       0.74147596, 0.70094557, 0.34934824, 0.45994395, 0.2552992 ,
       0.29412505, 0.83258785, 0.61539724, 0.55495876, 0.78612202,
       0.59856774, 0.52043747, 0.8397919 , 0.34737519, 0.22003974,
       0.54209857, 0.63391273, 0.59326018, 0.61500238, 0.46024664,
       0.2070782 , 0.60972505, 0.51268319, 0.18089938, 0.94453047,
       0.57114485, 0.80558165, 0.83455396, 0.48128052, 0.62467125,
       0.58070789, 0.02192396, 0.5521681 , 0.34634577, 0.01046063,
       0.50507557, 0.50137168, 0.41437769, 0.8057685 , 0.08600816,
       0.88524872, 0.07779401, 0.41909465, 0.13919337, 0.12085518,
       0.59362752, 0.5932869 , 0.23123523, 0.15081519, 0.33836539,
       0.10859077, 0.9747765 , 0.92461226, 0.20842271, 0.17096051,
       0.44743853, 0.2381667 , 0.69664664, 0.27239178, 0.08645858,
       0.8589519 , 0.50550392, 0.98997428, 0.29892487, 0.14736

In [ ]:
#Mesh 3D
z=15*np.random.random(100)
x=np.sin(z)
y=np.cos(z)
fig=go.Figure(data=[go.Mesh3d(x=x,y=y,z=z,opacity=0.5)])
fig.show()

In [ ]:
#plotting graph objects
#BUTTONS  #downward direction
#Scatter plot #Bar plot
import plotly.graph_objects as px
plot=px.Figure(data=[px.Scatter(x=x_,y=y_,mode="markers")])
#adding graph objects
plot.update_layout(
    updatemenus=[
                 dict(buttons=list([
                                    dict(
                                        args=["type","scatter"],
                                         label="Scatter plot",
                                         method="restyle"
                                    ),
                                    dict(
                                        args=["type","bar"],
                                         label="Bar plot",
                                         method="restyle"
                                        
                                    )
                 ]
                     
                 ),direction="down")
    ]
)
plot.show()




In [ ]:
import plotly.graph_objects as px
plot=px.Figure(data=[px.Scatter(x=x_,y=y_,mode="markers")])
#adding graph objects #buttons # upward direction
plot.update_layout(
    updatemenus=[
                 dict(buttons=list([
                                    dict(
                                        args=["type","scatter"],
                                         label="Scatter plot",
                                         method="restyle"
                                    ),
                                    dict(
                                        args=["type","bar"],
                                         label="Bar plot",
                                         method="restyle"
                                        
                                    )
                 ]
                     
                 ),direction="up")
    ]
)
plot.show()

In [ ]:
import plotly.graph_objects as px
plot=px.Figure(data=[px.Scatter(x=x_,y=y_,mode="markers")])
#adding graph objects #buttons # left direction
plot.update_layout(
    updatemenus=[
                 dict(type="buttons",   #adding the directions of buttons to left
                      direction="left",
                      buttons=list([
                                    dict(
                                        args=["type","scatter"],
                                         label="Scatter plot",
                                         method="restyle"
                                    ),
                                    dict(
                                        args=["type","bar"],
                                         label="Bar plot",
                                         method="restyle"
                                        
                                    )
                 ]
                     
                 ))
    ]
)
plot.show()

In [ ]:
#adding rangeslider
import plotly.graph_objects as px
import plotly.express as go 
x=df["total_bill"]
y=df["day"]
plot=px.Figure(data=[px.Scatter(x=x,y=y,mode="lines")])
plot.update_layout(
    xaxis=dict(
        rangeselector=dict(
            buttons=list([dict(count=1,step="day",stepmode="backward")])
        ),rangeslider=dict(visible=True)
    )
)
plot.show()

In [ ]:
df=go.data.gapminder()
df

country continent  year  ...   gdpPercap  iso_alpha  iso_num
0     Afghanistan      Asia  1952  ...  779.445314        AFG        4
1     Afghanistan      Asia  1957  ...  820.853030        AFG        4
2     Afghanistan      Asia  1962  ...  853.100710        AFG        4
3     Afghanistan      Asia  1967  ...  836.197138        AFG        4
4     Afghanistan      Asia  1972  ...  739.981106        AFG        4
...           ...       ...   ...  ...         ...        ...      ...
1699     Zimbabwe    Africa  1987  ...  706.157306        ZWE      716
1700     Zimbabwe    Africa  1992  ...  693.420786        ZWE      716
1701     Zimbabwe    Africa  1997  ...  792.449960        ZWE      716
1702     Zimbabwe    Africa  2002  ...  672.038623        ZWE      716
1703     Zimbabwe    Africa  2007  ...  469.709298        ZWE      716

[1704 rows x 8 columns]

In [ ]:
#ANIMATION FRAME
#HOVERNAME
fig=go.bar(df,x="continent",y="pop",color="lifeExp",animation_frame="year",hover_name="country",range_y=[0,4000000000])
fig.show()

In [ ]:
#without hovername we cannot see different countries names on bars
fig=go.bar(df,x="continent",y="pop",color="lifeExp",animation_frame="year",range_y=[0,4000000000])
fig.show()

In [ ]:
#Density contour
fig=go.density_contour(df,x="gdpPercap",y="lifeExp",color="continent",animation_frame="year",animation_group="country",marginal_y="histogram",range_y=[10,100])
fig.show()

In [ ]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv") #Apple finance chart
df

Date   AAPL.Open   AAPL.High  ...        mavg          up   direction
0    2015-02-17  127.489998  128.880005  ...  117.927667  129.114281  Increasing
1    2015-02-18  127.629997  128.779999  ...  118.940333  130.038244  Increasing
2    2015-02-19  128.479996  129.029999  ...  119.889167  130.884089  Decreasing
3    2015-02-20  128.619995  129.500000  ...  120.763500  131.741551  Increasing
4    2015-02-23  130.020004  133.000000  ...  121.720167  133.067817  Increasing
..          ...         ...         ...  ...         ...         ...         ...
501  2017-02-10  132.460007  132.940002  ...  124.498666  134.503328  Decreasing
502  2017-02-13  133.080002  133.820007  ...  125.205166  135.589534  Increasing
503  2017-02-14  133.470001  135.089996  ...  125.953499  136.731280  Increasing
504  2017-02-15  135.520004  136.270004  ...  126.723499  137.901963  Decreasing
505  2017-02-16  135.669998  135.899994  ...  127.504332  138.805366  Decreasing

[506 rows x 11 columns]

In [ ]:
fig=px.Figure([px.Scatter(x=df["Date"],y=df["AAPL.Close"])])
fig.show()

In [ ]:
#Candlestick chart is a style of financial chart used to describe price movements of a security,derivative,or currency
#rangeslider automatically enabled
#stocks exhange
#yahoo.api #real time data
fig=px.Figure(data=[px.Candlestick(x=df["Date"],open=df["AAPL.Open"],high=df["AAPL.High"],low=df["AAPL.Low"],close=df["AAPL.Close"])])
fig.show()

In [ ]:
fig=px.Figure(data=[px.Candlestick(x=df["Date"],open=df["AAPL.Open"],high=df["AAPL.High"],low=df["AAPL.Low"],close=df["AAPL.Close"])])
fig.update_layout(xaxis_rangeslider_visible=False)
fig.show()

In [ ]:
#changing the colours
fig=px.Figure(data=[px.Candlestick(x=df["Date"],open=df["AAPL.Open"],high=df["AAPL.High"],low=df["AAPL.Low"],close=df["AAPL.Close"],
                                   increasing_line_color="cyan",decreasing_line_color="gray")])
fig.update_layout(xaxis_rangeslider_visible=False)
fig.show()

In [ ]:
fig=px.Figure(data=[px.Candlestick(x=df["Date"],open=df["AAPL.Open"],high=df["AAPL.High"],low=df["AAPL.Low"],close=df["AAPL.Close"],
                                   increasing_line_color="cyan",decreasing_line_color="gray")])
fig.show()

In [ ]:
#displaying mapbox
from urllib.request import urlopen
import json
with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
  counties = json.load(response)
print(counties)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/fips-unemp-16.csv",
               dtype={"fips":str})
df

fips  unemp
0     01001    5.3
1     01003    5.4
2     01005    8.6
3     01007    6.6
4     01009    5.5
...     ...    ...
3214  72145   13.9
3215  72147   10.6
3216  72149   20.2
3217  72151   16.9
3218  72153   18.8

[3219 rows x 2 columns]

In [ ]:
#MAPBOX
from urllib.request import urlopen
import json
with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
  counties = json.load(response)

import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/fips-unemp-16.csv",
               dtype={"fips":str})

import plotly.express as px
fig=px.choropleth_mapbox(df, geojson=counties, locations='fips', color='unemp',
                          color_continuous_scale="Viridis",
                          range_color=(0,12),
                          mapbox_style="carto-positron",
                          zoom=3, center = {"lat": 37.0902, "lon": -95.7129},
                          opacity=0.5,
                          labels={'unemp':'unemployment rate'}
                          )
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()


Output hidden; open in https://colab.research.google.com to view.